networks:
  dev:

services:
  nginx:
    image: nginx
    container_name: game_store_nginx
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/photos:/usr/share/nginx/html/photos:ro
    depends_on:
      - app
    ports:
      - ${NGINX_HOST_PORT}:80

    networks:
      - dev

  app:
    container_name: game_store_backend
    build: ./
    depends_on:
      - db
    command:  uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/WebProjects/GameStore/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always 
    env_file: 
      -  .env
    networks:
      - dev

  db:
    container_name: game_store_db
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}

    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - dev
